가족 정보 화면 추가
Team-PATCH/Harmony-Android pull request #10
Opened 2024-10-22 13:09 UTC by agvber

<img src="https://github.com/user-attachments/assets/e78210d6-527e-440e-bd2e-8927ec61ca54" width=30% hight=30%/>

2024-10-23 10:44 UTC, theBettor approved these changes
<img width="782" alt="스크린샷 2024-10-23 오후 7 43 29" src="https://github.com/user-attachments/assets/ef03ee05-a8de-4e23-ba47-a90a3fbd596b">

에뮬레이터 돌리면 터지는 문제가 있습니다!

2024-10-23 10:59 UTC, agvber commented
> <img alt="스크린샷 2024-10-23 오후 7 43 29" width="782" src="https://private-user-images.githubusercontent.com/89888486/379228952-ef03ee05-a8de-4e23-ba47-a90a3fbd596b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODEwMzgsIm5iZiI6MTcyOTY4MDczOCwicGF0aCI6Ii84OTg4ODQ4Ni8zNzkyMjg5NTItZWYwM2VlMDUtYThkZS00ZTIzLWJhNDctYTkwYTNmYmQ1OTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEwNTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0N2I5MWY0ZDY2MzczMjE3ODgxYWQ2OWVjYzViOTM3ZjVhNWQ5OTVmOWEwNmQxNmEyZTU3MTlmYjA3ZDFhOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HSkiFW7OgpNKGdIkhfsMrIv1lGILE8-tk9I9y2sI8AU">
> 에뮬레이터 돌리면 터지는 문제가 있습니다!

아 인터넷 권한을 추가 안 했네요.. 수정하겠습니다

2024-10-23 13:18 UTC, agvber commented
@theBettor 버그 수정했습니다 문제 없으면 머지 부탁드립니다!

2024-10-23 15:53 UTC, agvber commented
@theBettor 문제 없으면 Merge 부탁드립니다!

2024-10-24 11:55 UTC, theBettor requested changes
이거 컴포넌트들은 지금 클릭해도 동작 안되는게 정상인거죠?

2024-10-24 12:48 UTC, agvber commented
> 이거 컴포넌트들은 지금 클릭해도 동작 안되는게 정상인거죠?

그죠? 가족 초대하기는 서버로부터 URL 가져와야 하니까 그렇고
설정, 프로필 수정은 아직 화면 연결을 안 해서 작동 안되죠

2024-10-26 17:11 UTC, DJDrama approved these changes

2024-10-27 15:35 UTC, theBettor approved these changes
커밋 하나하나 봤는데 경이롭군요.. 도대체 이런걸 어떻게..

2024-10-28 09:43 UTC, agvber commented
> 커밋 하나하나 봤는데 경이롭군요.. 도대체 이런걸 어떻게..

별거 아닙니다 찬교님도 충분히 하실 수 있습니다!!

2024-10-28 09:44 UTC, merged