Feature/profile edit
Team-PATCH/Harmony-Android pull request #15
Opened 2024-10-23 13:32 UTC by agvber

## 🤷‍♂️ Description
- 프로필 화면 추가
- 프로필 Android Jetpack Navgation 대응
- UiState 추가
- ErrorHandler 추가
- 프로필 수정 UseCase 추가
- 별도의 Component UI 추가

## 📸 Screenshots
<img src="https://github.com/user-attachments/assets/c859ff7d-2a8c-4b01-bb73-77b363fed8db" width=30% height=30%/>

2024-10-24 12:00 UTC, theBettor requested changes
https://github.com/user-attachments/assets/2b240d61-ad8d-4742-b342-03373b6145da

이렇게 동작하는게 정상인가요?

2024-10-24 12:49 UTC, agvber commented
> 2024-10-24.9.03.25.mov 
> 이렇게 동작하는게 정상인가요?

네 ViewModel에서 상태 관리하고 있기 때문에 ViewModel이 없는 Preview는 작동 안되는 것이 정상입니다

2024-10-25 06:51 UTC, DJDrama requested changes

2024-10-25 06:51 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    val getUserInfoUseCase: GetUserInfoUseCase
[TO-BE] private val getUserInfoUseCase: GetUserInfoUseCase

2024-10-25 06:51 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    private val _errorHandler: MutableSharedFlow<ProfileEditErrorHandler> = MutableSharedFlow()
에러이니 만큼 반드시 전달되어야 하니 channel로 변경하는 것은 어떠실까요?

2024-10-25 06:51 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    private val _profileEditUiState: MutableStateFlow<ProfileEditUiState> =
Compose에서는 sealed 보다는 data class로 관리하면 좋을 것 같습니다~!

(예)
```
data class ProfileEditState(
  val relation: String = "",
  val name: String = "",
  val profileImage: Image? = null,
)
```

2024-10-25 09:33 UTC, agvber commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    val getUserInfoUseCase: GetUserInfoUseCase
수정하겠습니다!😊

2024-10-25 09:38 UTC, agvber commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    private val _errorHandler: MutableSharedFlow<ProfileEditErrorHandler> = MutableSharedFlow()
SharedFlow 사용할 때 불안했는데 Channel이 있었네요 감사합니다

2024-10-25 09:47 UTC, agvber commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    private val _profileEditUiState: MutableStateFlow<ProfileEditUiState> =
그러면 화면 로딩 부분을 어떻게 체크하면 좋을까요?

Compose에서 sealed 상태 관리가 좀 힘들다고 생각 돼서 고민 하고 있었는데
아래와 같이 Side Effect sealed를 만들어서 상태 관리를 하는 건 어떻게 생각하시나요??

[FamilyInfoViewModel.kt](https://github.com/Team-PATCH/Harmony-Android/blob/feature/family_info/feature/family-info/src/main/java/com/teampatch/feature/family/info/FamilyInfoViewModel.kt)

    private val _sideEffect: Channel<FamilyInfoSideEffect> = Channel()
    val sidEffect: Flow<FamilyInfoSideEffect> = _sideEffect.receiveAsFlow()

    private val _familyInfoUiState = MutableStateFlow(FamilyInfoUiState())
    val familyInfoUiState = _familyInfoUiState.asStateFlow()

    private fun load() = viewModelScope.launch {
        try {
            val user = getUserInfoUseCase().first()
            val familyInfo = getFamilyInfoUseCase().first()
            _familyInfoUiState.value = FamilyInfoUiState(user, familyInfo)
            _sideEffect.send(FamilyInfoSideEffect.Load)
        } catch (e: Exception) {
            _sideEffect.send(FamilyInfoSideEffect.LoadError(e))
        }
    }


    fun inviteFamily() = viewModelScope.launch {
        try {
            inviteFamilyUseCase()
        } catch (e: Exception) {
            e.printStackTrace()
            _sideEffect.send(FamilyInfoSideEffect.InviteError(e))
        }
    }



@DJDrama

2024-10-26 17:03 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditScreen.kt
> +    var isLoading by rememberSaveable { mutableStateOf(true) }
viewModel 에서 mutableStateOf와 data class 로 아래 예시와 같이 쓰면 더 편할것입니다~!

viewmodel 에서
```
var state by mutableStateOf(ProfileEditState())
  private set

  fun doSomething(){
    state = state.copy(isLoading=true)
    // ... do something
    state = state.copy(isLoading=false)
  }
// ...
data class ProfileEditState(
  val isLoading: Boolean = false
)
```

2024-10-26 17:03 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/model/ProfileEditUiState.kt
> +    val profileImage: Image? = null
아 여기 있었네요 ㅋㅋ

여기에 val isLoading: Boolean = false 넣으셔서 관리하시면 될 것 같습니다~!

2024-10-26 17:04 UTC, DJDrama commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditViewModel.kt
> +    private val _profileEditUiState: MutableStateFlow<ProfileEditUiState> =
Init은 없애도 될 것 같습니다~! Load는 아래 isLoading으로 관리하면 될 것 같구요~!

2024-10-26 17:12 UTC, DJDrama approved these changes

2024-10-27 10:54 UTC, agvber commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/ProfileEditScreen.kt
> +    var isLoading by rememberSaveable { mutableStateOf(true) }
우와 사용해보니 너무 편하네요 compose함수에서는 사용하다가 왜 ViewModel에서 사용할 생각을 한번도 안 했네요!

근데 ViewModel에서는 Flow 결합 연산자들을(combine, merge, zip...) 자주 사용하게 되는데
지금은 필요 없지만 미리 대응하는 것은 오버엔지니어링일까요??

2024-10-27 10:54 UTC, agvber commented on feature/profile-edit/src/main/java/com/teampatch/feature/profile/edit/model/ProfileEditUiState.kt
> +    val profileImage: Image? = null
넵!

2024-10-28 04:11 UTC, theBettor approved these changes
잘 봤습니다!

2024-10-28 09:44 UTC, merged