온보딩 화면 추가
Team-PATCH/Harmony-Android pull request #19
Opened 2024-10-29 13:40 UTC by theBettor

## 🤷‍♂️ Description
resolved: #14 

- 시간만 지연되는 것 같고, 지피티도 다 써버려서 오늘 올리고 피드백 받으면서 수정하는게 좋을 것 같습니다...
- 피그마랑 비슷하지 않은 부분은 능력 부족으로 아직 수정 못했습니다.
- onBackRequest 같은 것도 계속 추가하고자 합니다.
- 다음 스텝인 nav나 카카오 로그인도 준비하겠습니다.
- 일과 두요!

2024-10-29 17:47 UTC, DJDrama approved these changes

2024-10-30 05:27 UTC, agvber requested changes

2024-10-30 05:27 UTC, agvber commented on app/build.gradle.kts
(58, 65)중복된 코드 수정 부탁 드립니다

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/proguard-rules.pro
사용하지 않는 파일 제거 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/androidTest/java/com/teampatch/feature/onboarding/login/ExampleInstrumentedTest.kt
사용하지 않는 파일 제거 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Theme.kt
중복된 파일 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Type.kt
중복된 파일 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/res/values/strings.xml
Activity를 안 쓰는 것 같은데 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/res/values/themes.xml
Activity를 안 쓰는 것 같은데 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/test/java/com/teampatch/feature/onboarding/login/ExampleUnitTest.kt
안 쓰시는 파일 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Color.kt
중복된 파일 삭제 부탁드립니다!

2024-10-30 05:27 UTC, agvber commented on feature/onboarding/login/src/main/AndroidManifest.xml
Activity가 없는 것 같아요! 삭제 부탁드립니다!

2024-10-30 12:08 UTC, DJDrama approved these changes

2024-10-31 13:10 UTC, theBettor reviewed
일부 수정했습니다. 확인 해주세요! @agvber

2024-10-31 13:10 UTC, theBettor commented on app/build.gradle.kts
해결 완료

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/androidTest/java/com/teampatch/feature/onboarding/login/ExampleInstrumentedTest.kt
이런건 어떻게 찾아내시는 겁니까... 삭제 완료 @agvber

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/proguard-rules.pro
이것도 삭제 완료

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/AndroidManifest.xml
Activity 부분만 삭제하면 되는거겠죠?

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Color.kt
중복 아닌거 같은데용?? @agvber

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Theme.kt
이것도 뭐가 중복된지 모르겠습니다 @agvber

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Type.kt
@agvber 이것도 뭐가 중복인지 모르겠어여

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/res/values/strings.xml
수정 완료

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/main/res/values/themes.xml
수정 완료

2024-10-31 13:10 UTC, theBettor commented on feature/onboarding/login/src/test/java/com/teampatch/feature/onboarding/login/ExampleUnitTest.kt
수정 완료

2024-10-31 13:55 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Theme.kt
[theme](https://github.com/Team-PATCH/Harmony-Android/tree/develop/core/designsystem/src/main/java/com/teampatch/core/designsystem/theme)

designsystem 모듈에 이미 존재합니다!

2024-10-31 13:55 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Theme.kt
@theBettor

2024-10-31 13:58 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
문자열들은 string.xml 파일에 담아주세요!

2024-10-31 13:58 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
사용하지 않는(주석 처리된) 코드들은 제거 부탁드립니다!

2024-10-31 13:59 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
사용하지 않는(주석 처리된) 코드들은 제거 부탁드립니다!

2024-10-31 14:00 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
파일을 화면 단위로 나눠주세요 너무 많아서 읽기 힘듭니다

2024-10-31 14:10 UTC, agvber commented on feature/onboarding/login/src/main/AndroidManifest.xml
넵!

2024-10-31 14:12 UTC, agvber commented
![image](https://github.com/user-attachments/assets/b1e867e5-6ad5-4c0e-b4df-c34523dd7a8f)

모듈이름을 :onboarding:login -> :onboarding으로 변경하는 건 어떨까요??

2024-10-31 15:19 UTC, agvber commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnBoardingViewModel.kt
> +    fun login(invitationCode: String): LiveData<Result<FamilyGroup>> = liveData {
LiveData를 직접 return 하시는데
Compose 함수에서 어떤 식으로 observing 하는 지 보여주실 수 있나요??

2024-11-05 10:56 UTC, closed without merging

2024-11-05 11:45 UTC, theBettor reviewed
나머지도 확인 부탁드립니다 바로 푸시할게여

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnBoardingViewModel.kt
> +    fun login(invitationCode: String): LiveData<Result<FamilyGroup>> = liveData {
오 어떻게 보여드리면 되는걸까요? LiveData는 임의로 쓰고 있는거긴 합니다

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
정리 완료했습니다.  https://github.com/Team-PATCH/Harmony-Android/issues/22 여기 참고 해주세요.

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
주석은 나중에 지워도 될까요...

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/OnboardingScreen.kt
예시를 들어주실 수 있으실까용? 이건 나중에 온라인에서 만나야겠네여

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Type.kt
수정 완료

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Theme.kt
수정 완료

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/java/com/teampatch/feature/onboarding/login/ui/theme/Color.kt
수정 완료

2024-11-05 11:45 UTC, theBettor commented on feature/onboarding/login/src/main/AndroidManifest.xml
수정 완료