Feature/memory card registration
Team-PATCH/Harmony-Android pull request #33
Opened 2024-11-15 19:31 UTC by agvber

## 🤷‍♂️ PR 내용(Issue 꼭 달기!)
- common 모듈 추가
- data 모듈 추가
- 타이핑 애니메이션 텍스트 추가
- 추억카드 등록 화면추가
- designsystem utils 폴더 정리

## 🅿️
<img src="https://github.com/user-attachments/assets/108fb5bb-7d18-4881-aaed-1f98be2482bb" width=30% height=30%/>

2024-11-19 08:35 UTC, DJDrama requested changes
고생많으셨습니다! 엄청 열심히 하셨네요!

2024-11-19 08:35 UTC, DJDrama commented on core/data/src/main/java/com/teampatch/core/data/repository/MemoryCardRepositoryImpl.kt
> +        if (!appContext.checkRadioAudioPermission()) {
permission checking은 presentation layer에서 진행되어야 합니다!
UI 단에서 startRecord 함수를 호출하기전에 수행되면 좋을 것 같습니다~!

2024-11-19 08:35 UTC, DJDrama commented on core/data/src/main/java/com/teampatch/core/data/repository/MemoryCardRepositoryImpl.kt
> +        return@withContext FileInputStream(fileName)
repository에서는 파일을 저장하는 정도로만 코드를 남기는 것이 좋을 것같습니다.

MyMediaRecorderService 같이 클래스를 따로 빼서, 그 안에서 stop, release, close 등 MediaRecorder 관련 코드를 작성하느 것이 좋을 것 같습니다~!

2024-11-19 08:35 UTC, DJDrama commented on core/designsystem/src/main/java/com/teampatch/core/designsystem/component/DefaultButton.kt
>      enable: Boolean = true,
사소한 것이지만, enable 보다는 enabled, 아니면 isEnabled 형태면 더 좋을 것 같습니다~!

2024-11-19 08:35 UTC, DJDrama commented on core/designsystem/src/main/java/com/teampatch/core/designsystem/component/TypewriterText.kt
> +fun TypewriterText(
Typewriter -> TypeWriter

2024-11-19 08:35 UTC, DJDrama commented on feature/memorycard-registration/src/main/java/com/teampatch/feature/memorycard/registration/MemoryCardRegistrationViewModel.kt
> +        }
```
catch (e: PermissionDeniedException) {
     e.printStackTrace()
_sideEffect.send(MemoryCardRegistrationSideEffect.RecordingPermissionDeniedError)
    uiState = uiState.copy(recordState = RecordState.INIT)
 } catch(e: Exception) {
     e.printStackTrace()
    _sideEffect.send(MemoryCardRegistrationSideEffect.RecordingError)
    uiState = uiState.copy(recordState = RecordState.INIT)
}
```

2024-11-19 08:35 UTC, DJDrama commented on feature/memorycard-registration/src/main/java/com/teampatch/feature/memorycard/registration/MemoryCardRegistrationViewModel.kt
> +                isRecordFinished = { uiState.recordState == RecordState.COMPLETE }
콜백 메소드로 쓰게 되면 둘간의 커플링이 심해지기 때문에, usecase에서 true나 false를 리턴시켜서 true면 COMPLETE으로 바꾼다던지 처리하면 더 좋을 것 같습니다~!

왜냐하면 만약 data 레이어에서 isRecordFinished 관련해서 누군가 작업을 하다가 필요없어 보여 코드를 지우더라도 다른 레이어에 영향을 안줘야 클린한 코드가 되는데, 만약 지우게 되면 유즈케이스, 뷰모델 모두 오류가 발생할 것이기에 커플링을 낮추면 좋을 것 같습니다~!

2024-11-19 08:43 UTC, agvber commented on core/designsystem/src/main/java/com/teampatch/core/designsystem/component/DefaultButton.kt
>      enable: Boolean = true,
넵 수정하겠습니다!

2024-11-19 08:44 UTC, agvber commented on core/designsystem/src/main/java/com/teampatch/core/designsystem/component/TypewriterText.kt
> +fun TypewriterText(
수정하겠습니다!

2024-11-19 08:46 UTC, agvber commented on feature/memorycard-registration/src/main/java/com/teampatch/feature/memorycard/registration/MemoryCardRegistrationViewModel.kt
> +        }
코드 중복 문제로 if 문으로 변경하였는데....
일단은 수정하겠습니다

2024-11-19 08:52 UTC, agvber commented on feature/memorycard-registration/src/main/java/com/teampatch/feature/memorycard/registration/MemoryCardRegistrationViewModel.kt
> +                isRecordFinished = { uiState.recordState == RecordState.COMPLETE }
Presentation layer에서 녹음 중단 버튼을 클릭하는 경우 callback 메소드로 체크하는 방법이 좋을 것 같다고 생각했는데 직지금 다시 보니까 usecase가 2가지 action을 하고 있어서 좋은 방법은 아닌 것 같네요

처음부터 MyMediaRecorderService를 Singleton으로 만들고 상태에 따라서 중단 시작을 해야 할 것 같네요
감사합니다!

2024-11-19 08:53 UTC, agvber commented
> 고생많으셨습니다! 엄청 열심히 하셨네요!

코드가 많았는데 정성이 담긴 코드리뷰 감사합니다
(너무 재밌어요 😊😊😊😊😊)

2024-11-19 08:54 UTC, agvber commented on core/data/src/main/java/com/teampatch/core/data/repository/MemoryCardRepositoryImpl.kt
> +        return@withContext FileInputStream(fileName)
음 고민 했던 부분이였는데 감사합니다

2024-11-19 10:56 UTC, DJDrama commented on feature/memorycard-registration/src/main/java/com/teampatch/feature/memorycard/registration/MemoryCardRegistrationViewModel.kt
> +        }
아 아뇨 그냥 이렇게 고려해보는것도 괜찮다 이겁니다! 틀렸다는게 아닙니다 @agvber

2024-11-20 11:26 UTC, theBettor approved these changes
common, data 모듈의 코드들은 생소하네요 잘 봤습니다!!

2024-11-22 10:43 UTC, DJDrama approved these changes

2024-11-22 16:44 UTC, merged